'use strict';
const motionPreference = matchMedia('(prefers-reduced-motion: reduce)');
let reduced = motionPreference.matches;
document.documentElement.classList.add('js');
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const menu=document.querySelector('#menu'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}});
document.querySelectorAll('[data-service]').forEach(a=>a.addEventListener('click',()=>{document.querySelector('#service').value=a.dataset.service}));
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();const name=document.querySelector('#name').value.trim();if(!name){document.querySelector('#name').focus();return}const service=document.querySelector('#service').value,message=document.querySelector('#message').value.trim();const text=`Olá, BGTech Consulting! Meu nome é ${name}. Tenho interesse em ${service}.${message?'\n\n'+message:''}`;window.location.href='https://wa.me/5511920193443?text='+encodeURIComponent(text)});document.querySelector('#year').textContent=new Date().getFullYear();
if(!reduced&&matchMedia('(pointer: fine)').matches)document.querySelectorAll('.service').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.transform=`perspective(1000px) rotateX(${-(e.clientY-r.top-r.height/2)/65}deg) rotateY(${(e.clientX-r.left-r.width/2)/55}deg)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
const canvas=document.querySelector('#orb'),ctx=canvas.getContext('2d');let w=0,h=0,rotation=.3,px=0,py=0,paused=reduced,visible=true,last=0;const points=[];const count=matchMedia('(max-width: 700px)').matches?420:780;for(let i=0;i<count;i++){const y=1-2*i/(count-1),r=Math.sqrt(1-y*y),theta=i*Math.PI*(3-Math.sqrt(5));points.push([Math.cos(theta)*r,y,Math.sin(theta)*r])}
function resize(){const b=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);w=b.width;h=b.height;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);draw()}function project(x,y,z){const a=rotation+px*.3,ca=Math.cos(a),sa=Math.sin(a),xx=x*ca-z*sa,zz=x*sa+z*ca,b=.2+py*.2,yy=y*Math.cos(b)-zz*Math.sin(b),zzz=y*Math.sin(b)+zz*Math.cos(b),scale=Math.min(w*.34,h*.36),p=3.7/(3.7-zzz);return{x:w*.52+xx*scale*p,y:h*.47+yy*scale*p,z:zzz,p}}function draw(){if(!ctx)return;ctx.clearRect(0,0,w,h);const cx=w*.52,cy=h*.47,s=Math.min(w*.34,h*.36);const glow=ctx.createRadialGradient(cx,cy,s*.12,cx,cy,s*1.65);glow.addColorStop(0,'#1453dd33');glow.addColorStop(.5,'#1642ad18');glow.addColorStop(1,'#10245c00');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);for(let ring=0;ring<3;ring++){ctx.beginPath();for(let i=0;i<=180;i++){const t=i/180*Math.PI*2,r=1.32;let x=Math.cos(t)*r,y=Math.sin(t)*r*.24,z=Math.sin(t)*r;if(ring===1){y=Math.sin(t)*r;x=Math.cos(t)*r*.65;z=Math.cos(t)*r*.6}if(ring===2){y=Math.sin(t)*r*.75;x=Math.cos(t)*r;z=-Math.sin(t)*r*.7}const q=project(x,y,z);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)}ctx.strokeStyle=ring===0?'#4689fa60':'#345aab40';ctx.lineWidth=.8;ctx.stroke()}const projected=points.map(p=>project(...p));for(let i=0;i<projected.length;i++){const a=projected[i];for(const d of [13,21]){const b=projected[i+d];if(!b||a.z<-.35||b.z<-.35)continue;const dist=Math.hypot(a.x-b.x,a.y-b.y);if(dist<s*.24){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=`rgba(49,123,242,${.11*(a.z+1)})`;ctx.lineWidth=.6;ctx.stroke()}}}projected.sort((a,b)=>a.z-b.z).forEach(q=>{const alpha=.18+(q.z+1)*.35;ctx.beginPath();ctx.arc(q.x,q.y,Math.max(.65,q.p*1.25),0,Math.PI*2);ctx.fillStyle=`rgba(${q.z>.65?'90,218,255':'63,130,248'},${alpha})`;ctx.fill()});}
canvas.addEventListener('pointermove',e=>{if(reduced||paused)return;const b=canvas.getBoundingClientRect();px=(e.clientX-b.left)/w-.5;py=(e.clientY-b.top)/h-.5});new ResizeObserver(resize).observe(canvas);new IntersectionObserver(e=>visible=e[0].isIntersecting).observe(canvas);function frame(t){if(!paused&&visible&&!document.hidden&&t-last>32){rotation+=.003;draw();last=t}requestAnimationFrame(frame)}if(ctx)requestAnimationFrame(frame);

// Efeitos coordenados: progresso, luz e entradas escalonadas.
motionPreference.addEventListener('change',e=>{reduced=e.matches;paused=reduced;});
const progress=document.createElement('div');progress.className='scroll-progress';progress.setAttribute('aria-hidden','true');document.body.append(progress);
let scrollPending=false;
function updateScroll(){const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform='scaleX('+(max>0?scrollY/max:0)+')';scrollPending=false;}
addEventListener('scroll',()=>{if(!scrollPending){scrollPending=true;requestAnimationFrame(updateScroll)}},{passive:true});addEventListener('resize',updateScroll);updateScroll();
document.querySelectorAll('.services,.steps').forEach(group=>group.querySelectorAll('.reveal').forEach((el,i)=>el.style.transitionDelay=(i*85)+'ms'));
if(matchMedia('(pointer: fine)').matches){
 document.querySelectorAll('.service,.primary,.nav-cta').forEach(el=>el.addEventListener('pointermove',e=>{if(reduced)return;const r=el.getBoundingClientRect();el.style.setProperty('--light-x',((e.clientX-r.left)/r.width*100)+'%');el.style.setProperty('--light-y',((e.clientY-r.top)/r.height*100)+'%');}));
}
const atmospheres=document.querySelectorAll('.hero,.statement,.contact');
const atmosphereObserver=new IntersectionObserver(items=>items.forEach(item=>item.target.classList.toggle('fx-visible',item.isIntersecting)));
atmospheres.forEach(el=>atmosphereObserver.observe(el));
document.addEventListener('visibilitychange',()=>document.body.classList.toggle('page-hidden',document.hidden));
